import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.ops.roi_align as roi_align

import numpy as np
import math
import logging

from lib.backbones.dla import dla34, dla102, dla60, dla169
from lib.backbones.dlaup import DLAUp, DLAUpv2
from utils.misc import NestedTensor
from lib.models.position_encoding import build_position_encoding
from lib.losses.loss_function import extract_input_from_tensor
from lib.helpers.decode_helper import _topk,_nms

from lib.models.transformer import DeformableTransformerDecoderLayer, DeformableTransformerDecoder
from lib.models.transformer import DeformableTransformerEncoderLayer, DeformableTransformerEncoder
import wandb

def weights_init_xavier(m):
    classname = m.__class__.__name__
    if classname.find('Linear') != -1:
        nn.init.xavier_uniform_(m.weight)
        if m.bias is not None:
            nn.init.constant_(m.bias, 0.0)
    elif classname.find('Conv') != -1:
        nn.init.xavier_uniform_(m.weight)
        if m.bias is not None:
            nn.init.constant_(m.bias, 0.0)
    elif classname.find('MSDeformAttn') != -1:  
        if hasattr(m, '_reset_parameters'):  
            m._reset_parameters()
        else:
            for p in m.parameters():
                if p.dim() > 1:
                    nn.init.xavier_uniform_(p)     
    elif classname.find('BatchNorm') != -1:
        if m.affine:
            nn.init.constant_(m.weight, 1.0)
            nn.init.constant_(m.bias, 0.0)
 

class RARE(nn.Module):
    def __init__(self, backbone='dla34', neck='DLAUp', downsample=4, mean_size=None, cfg= None):
        assert downsample in [4, 8, 16, 32]
        super().__init__()
        self.roi_size = 7
        self.num_queries = 50
        self.num_hypo = 3
        self.cfg = cfg['model']
        self.cfg_parent = cfg
        self.num_classes = len(self.cfg_parent['dataset']['writelist'])

        self.get_backbone_features = False if 'get_backbone_features'  not in self.cfg_parent['tester'].keys() else self.cfg_parent['tester']['get_backbone_features']
        self.backbone = globals()[backbone](pretrained=True, return_levels=True)
        self.hidden_dim = 256  # default setting for head conv
        self.mean_size = nn.Parameter(torch.tensor(mean_size,dtype=torch.float32),requires_grad=False)
        self.cls_num = mean_size.shape[0]
        channels = self.backbone.channels  # channels list for feature maps generated by backbone
        self.first_level = int(np.log2(downsample))
        
        scales = [2 ** i for i in range(len(channels[self.first_level:]))]
        self.feat_up = globals()[neck](channels[self.first_level:], scales_list=scales)
        

        self.proj = nn.Sequential(
            nn.Conv2d(channels[self.first_level], self.hidden_dim, kernel_size=(1, 1)),)
            # nn.GroupNorm(32, self.hidden_dim))
        self.upsample1 = nn.Sequential(
            nn.Conv2d(channels[self.first_level+1], self.hidden_dim, kernel_size=(1, 1)),)
            # nn.GroupNorm(32, self.hidden_dim))
        self.upsample2 = nn.Sequential(
            nn.Conv2d(channels[self.first_level+2], self.hidden_dim, kernel_size=(1, 1)),)
            # nn.GroupNorm(32, self.hidden_dim))
        
        # initialize the head of pipeline, according to heads setting.
        self.heatmap = nn.Sequential(nn.Conv2d(self.hidden_dim, self.hidden_dim, kernel_size=3, padding=1, bias=True),
                                     nn.ReLU(inplace=True),
                                     nn.Conv2d(self.hidden_dim, self.num_classes, kernel_size=1, stride=1, padding=0, bias=True))
        self.offset_2d = nn.Sequential(nn.Conv2d(self.hidden_dim, self.hidden_dim, kernel_size=3, padding=1, bias=True),
                                     nn.ReLU(inplace=True),
                                     nn.Conv2d(self.hidden_dim, 2, kernel_size=1, stride=1, padding=0, bias=True))
        self.size_2d = nn.Sequential(nn.Conv2d( self.hidden_dim, self.hidden_dim, kernel_size=3, padding=1, bias=True),
                                     nn.ReLU(inplace=True),
                                     nn.Conv2d(self.hidden_dim, 2, kernel_size=1, stride=1, padding=0, bias=True))
        
        self.num_feature_levels = cfg['model']['num_feature_levels']
        self.pos_embedding = build_position_encoding(self.cfg, self.hidden_dim)

        self.input_proj = nn.ModuleList()
        for _ in range(self.num_feature_levels):
            self.input_proj.append(
                nn.Sequential(
                    nn.Conv2d(self.backbone.channels[self.first_level + _], self.hidden_dim, kernel_size=1),
                    # nn.ReLU(inplace=True),
                    # nn.Linear(self.hidden_dim, self.hidden_dim)
                    # nn.GroupNorm(32, self.hidden_dim),
                )
            )
        # For 2D-to-3D Lifting
        self.query_proj = nn.ModuleList([
            nn.Sequential(
                nn.Conv2d((self.hidden_dim+2+self.cls_num), self.hidden_dim, kernel_size=self.roi_size),
                # nn.ReLU(inplace=True),
            ) for _ in range(self.num_hypo)
        ])
        
        self.pos_trans = nn.ModuleList([nn.Linear(self.hidden_dim, self.hidden_dim) for _ in range(self.num_hypo)])
        self.pos_norm  = nn.ModuleList([nn.LayerNorm(self.hidden_dim) for _ in range(self.num_hypo)])

        num_layers = 3
        encoder_layer = DeformableTransformerEncoderLayer(self.hidden_dim, self.hidden_dim, 0.1, "relu", self.num_feature_levels, 8, 4)  #d_model, dim_feedforward, dropout, activation, num_feature_levels, nhead, dec_n_points
        self.encoder = DeformableTransformerEncoder(encoder_layer, num_layers=num_layers)

        decoder_layer = DeformableTransformerDecoderLayer(self.hidden_dim, self.hidden_dim, 0.1, "relu", self.num_feature_levels, 8, 4)  #d_model, dim_feedforward, dropout, activation, num_feature_levels, nhead, dec_n_points
        self.decoder = DeformableTransformerDecoder(decoder_layer, num_layers=num_layers, return_intermediate=False)

        
        self.offset_3d = nn.Sequential(
            nn.Linear(self.hidden_dim, self.hidden_dim),
            nn.BatchNorm1d(self.hidden_dim),
            nn.ReLU(inplace=True),
            nn.Linear(self.hidden_dim, 2) 
        )
        self.size_3d = nn.Sequential(
            nn.Linear(self.hidden_dim, self.hidden_dim),
            nn.BatchNorm1d(self.hidden_dim),
            nn.ReLU(inplace=True),
            nn.Linear(self.hidden_dim, 4)  
        )
        self.heading = nn.Sequential(
            nn.Linear(self.hidden_dim, self.hidden_dim),
            nn.BatchNorm1d(self.hidden_dim),
            nn.ReLU(inplace=True),
            nn.Linear(self.hidden_dim, 24)  
        )
        self.depth = nn.Sequential(
            nn.Linear(self.hidden_dim, self.hidden_dim),  
            nn.LeakyReLU(inplace=True),
            nn.Linear(self.hidden_dim, 2) 
        )

        # === IoU-confidence head (conf only) ===
        self.iou3d_conf = nn.Sequential(
            nn.Linear(self.hidden_dim, self.hidden_dim),  
            nn.BatchNorm1d(self.hidden_dim),
            nn.ReLU(inplace=True),
            # nn.Linear(self.hidden_dim, self.hidden_dim),
            # nn.BatchNorm1d(self.hidden_dim),
            # nn.ReLU(inplace=True),
            nn.Linear(self.hidden_dim, 1),
            nn.Sigmoid()
        )

        # init layers
        for proj in self.input_proj:
            nn.init.xavier_uniform_(proj[0].weight, gain=1)
            nn.init.constant_(proj[0].bias, 0)

        self.heatmap[-1].bias.data.fill_(-2.19)
        self.fill_fc_weights(self.offset_2d)
        self.fill_fc_weights(self.size_2d)
        
        self.proj.apply(weights_init_xavier)
        self.upsample1.apply(weights_init_xavier)
        self.upsample2.apply(weights_init_xavier)
        
        for qp in self.query_proj:
            qp.apply(weights_init_xavier)
        
        self.encoder.apply(weights_init_xavier)
        self.decoder.apply(weights_init_xavier)
        
        for pos_tran in self.pos_trans:
            pos_tran.apply(weights_init_xavier)

        self.depth.apply(weights_init_xavier)
        self.offset_3d.apply(weights_init_xavier)
        self.size_3d.apply(weights_init_xavier)
        self.heading.apply(weights_init_xavier)
        self.iou3d_conf.apply(weights_init_xavier)


    def forward(self, input, coord_ranges, calibs, targets=None, K=50, mode='train'):
        device_id = input.device
        BATCH_SIZE = input.size(0)

        feats = self.backbone(input)
        
        # multi-scale
        multi_feats = self.feat_up(feats[self.first_level:])[:self.num_feature_levels]  # now returns list

        src_4 = self.proj(multi_feats[0])
        src_8 = self.upsample1(F.interpolate(multi_feats[1], size=src_4.shape[-2:], mode='bilinear'))
        src_16 = self.upsample2(F.interpolate(multi_feats[2], size=src_4.shape[-2:], mode='bilinear'))
        
                    
        agg_feat = (src_4 + src_8 + src_16) / 3

        ret = {}
        ret['heatmap']=self.heatmap(agg_feat)
        ret['offset_2d']=self.offset_2d(agg_feat)
        ret['size_2d']=self.size_2d(agg_feat)

        valid_masks = []
        pos_embeds = []
        srcs = []
        
        for l, feat in enumerate(multi_feats):
            B, C, H, W = feat.shape
            m = torch.zeros(B, H, W, dtype=torch.bool, device=feat.device)  
            valid_masks.append(m)
            nested = NestedTensor(feat, m)
            pos = self.pos_embedding(nested)
            pos_embeds.append(pos)
            srcs.append(self.input_proj[l](feat))
            
        #two stage
        assert(mode in ['train','val','test'])
        if mode=='train':   #extract train structure in the train (only) and the val mode
            inds,cls_ids = targets['indices'],targets['cls_ids']
            masks = targets['mask_2d'].bool()
        else:    #extract test structure in the test (only) and the val mode
            inds, cls_ids = _topk(_nms(torch.clamp(ret['heatmap'].sigmoid(), min=1e-4, max=1 - 1e-4)), K=K)[1:3]
            masks = torch.ones(inds.size()).type(torch.uint8).to(device_id).bool()
            inds = inds.type(torch.int64).to(device_id)
            cls_ids = cls_ids.type(torch.int64).to(device_id) 
        
        ret.update(self.get_roi_feat(agg_feat, inds, masks, srcs, valid_masks, pos_embeds, ret, calibs, coord_ranges, cls_ids))
        return ret

    def get_roi_feat_by_mask(self,feat, box2d_maps, inds, mask, calibs, coord_ranges, cls_ids, ret, srcs, valid_masks, pos_embeds):
        BATCH_SIZE,D,HEIGHT,WIDE = feat.size()
        device_id = feat.device
        num_masked_bin = mask.sum()
        
        res = {}
        heatmap_c = ret['heatmap'].clone()  
        B, C, H_map, W_map = ret['heatmap'].shape
        heatmap_flatten = heatmap_c.view(B, C, -1).clone()  # [B, C, H * W] and C is the number of classes

        batch_indices = torch.arange(B, device=heatmap_c.device).view(-1, 1).expand(B, inds.size(1))  # [B, max_obj]
        masked_batch_indices = batch_indices.masked_select(mask)  
        masked_cls_ids = cls_ids.masked_select(mask)  
        masked_inds = inds.masked_select(mask)  

        heatmap_flatten[masked_batch_indices, masked_cls_ids, masked_inds] = -float('inf')  
        heatmap_c = heatmap_flatten.reshape(B, C, H_map, W_map)
        
        num_gt_rois = mask.sum(dim=1)  
        num_to_add = (self.num_queries - num_gt_rois).clamp(min=0) 

        inds_filled = torch.full_like(inds, 0, device=device_id)  
        cls_ids_filled = torch.full_like(cls_ids, 0, device=device_id)  
        mask_filled = torch.zeros_like(mask, dtype=torch.bool, device=device_id)

        gt_indices_list = []
        o_num_mask_bin = mask.sum()
        
        for b in range(BATCH_SIZE):
            gt_indices = torch.nonzero(mask[b], as_tuple=True)[0]  
            gt_indices_list.append(gt_indices)

            inds_filled[b, gt_indices] = inds[b, gt_indices]
            cls_ids_filled[b, gt_indices] = cls_ids[b, gt_indices]
            mask_filled[b, gt_indices] = True  
    
            num_add = num_to_add[b].item()  
    
            if num_add > 0:
                b_heatmap = heatmap_c[b].unsqueeze(0)
                topk_inds, topk_cls_ids = _topk(_nms(torch.clamp(b_heatmap.sigmoid(), min=1e-4, max=1 - 1e-4)), K=num_to_add[b].item())[1:3]
                add_indices = torch.nonzero(~mask[b], as_tuple=True)[0][:num_add]

                inds_filled[b, add_indices] = topk_inds
                cls_ids_filled[b, add_indices] = topk_cls_ids.to(dtype=torch.long) 
                mask_filled[b, add_indices] = True  
        
        num_masked_bin = mask_filled.sum().item()  

        if num_masked_bin!=0:
            scale_box2d_masked = extract_input_from_tensor(box2d_maps, inds_filled, mask_filled)
        
            roi_feature_masked = roi_align(feat, scale_box2d_masked, [self.roi_size, self.roi_size])  # [B, num_queries, C, 7, 7]
            
            coord_ranges_mask2d = coord_ranges[scale_box2d_masked[:,0].long()]

            #map box2d coordinate from feature map size domain to original image size domain
            box2d_masked = torch.cat([scale_box2d_masked[:,0:1],
                       scale_box2d_masked[:,1:2]/WIDE  *(coord_ranges_mask2d[:,1,0:1]-coord_ranges_mask2d[:,0,0:1])+coord_ranges_mask2d[:,0,0:1],
                       scale_box2d_masked[:,2:3]/HEIGHT*(coord_ranges_mask2d[:,1,1:2]-coord_ranges_mask2d[:,0,1:2])+coord_ranges_mask2d[:,0,1:2],
                       scale_box2d_masked[:,3:4]/WIDE  *(coord_ranges_mask2d[:,1,0:1]-coord_ranges_mask2d[:,0,0:1])+coord_ranges_mask2d[:,0,0:1],
                       scale_box2d_masked[:,4:5]/HEIGHT*(coord_ranges_mask2d[:,1,1:2]-coord_ranges_mask2d[:,0,1:2])+coord_ranges_mask2d[:,0,1:2]],1)
            roi_calibs = calibs[box2d_masked[:,0].long()]

            box2d_height = torch.clamp(box2d_masked[:,4]-box2d_masked[:,2], min=1.0)

            #project the coordinate in the normal image to the camera coord by calibs
            coords_in_camera_coord = torch.cat([self.project2rect(roi_calibs,torch.cat([box2d_masked[:,1:3],torch.ones([num_masked_bin,1]).to(device_id)],-1))[:,:2],
                                          self.project2rect(roi_calibs,torch.cat([box2d_masked[:,3:5],torch.ones([num_masked_bin,1]).to(device_id)],-1))[:,:2]],-1)
            coords_in_camera_coord = torch.cat([box2d_masked[:,0:1],coords_in_camera_coord],-1)
            #generate coord maps
            coord_maps = torch.cat([torch.cat([coords_in_camera_coord[:,1:2]+i*(coords_in_camera_coord[:,3:4]-coords_in_camera_coord[:,1:2])/(self.roi_size-1) for i in range(self.roi_size)],-1).unsqueeze(1).repeat([1,self.roi_size,1]).unsqueeze(1),
                                torch.cat([coords_in_camera_coord[:,2:3]+i*(coords_in_camera_coord[:,4:5]-coords_in_camera_coord[:,2:3])/(self.roi_size-1) for i in range(self.roi_size)],-1).unsqueeze(2).repeat([1,1,self.roi_size]).unsqueeze(1)],1)

            #concatenate coord maps with feature maps in the channel dim
            cls_hots = torch.zeros(num_masked_bin,self.cls_num).to(device_id)
            
            #################### 6/24 cls_ids vs. cls_ids_filled 확인하기
            cls_hots[torch.arange(num_masked_bin).to(device_id),cls_ids_filled[mask_filled].long()] = 1.0
            # cls_hots[torch.arange(num_masked_bin).to(device_id),cls_ids[mask_filled].long()] = 1.0

            roi_feature_masked = torch.cat([roi_feature_masked, coord_maps, cls_hots.unsqueeze(-1).unsqueeze(-1).repeat([1, 1, self.roi_size, self.roi_size])],1)

            # new update 09.26.2025 for multiple queries
            q_list = [qp(roi_feature_masked).view(BATCH_SIZE, self.num_queries, -1) for qp in self.query_proj]  # [B, Q, C]
            q_bqhc = torch.stack(q_list, dim=2)          # [B, Q, H, C]
            roi_features_attn = q_bqhc.reshape(BATCH_SIZE, self.num_queries*self.num_hypo, -1)    # [B, Q*H, C]   e.g., [16, 250, 256]  #query=50, #H=5
            
            # normalized the 2D center
            x1, y1, x2, y2 = scale_box2d_masked[:, 1], scale_box2d_masked[:, 2], scale_box2d_masked[:, 3], scale_box2d_masked[:, 4]
        
            # Compute center coordinates
            cx = ((x1 + x2) / 2 / WIDE)
            cy = ((y1 + y2) / 2 / HEIGHT)

            ref_base = torch.stack([cx, cy], dim=-1).view(B, self.num_queries, 2)  # [B, Q, 2]
            pos_base = self.get_proposal_pos_embed(ref_base.detach())  # [B, Q, C]
            pos_list = [self.pos_norm[h](self.pos_trans[h](pos_base)) for h in range(self.num_hypo)]      # K × [B, Q, C]
            pos_bqhc = torch.stack(pos_list, dim=2)                           # [B, Q, H, C]
            query_embed_list  = pos_bqhc.reshape(B, self.num_queries*self.num_hypo, -1)     # [B, QH, C]
            reference_points = ref_base.unsqueeze(2).expand(B, self.num_queries, self.num_hypo, 2).reshape(B, self.num_queries*self.num_hypo, 2)  # [B, QH, 2]            
            
            # multi-scale Value feature
            src_flatten = []
            mask_flatten = []
            lvl_pos_embed_flatten = []
            spatial_shapes = []
            for lvl, (src, m, pos) in enumerate(zip(srcs, valid_masks, pos_embeds)):
                B, C, H, W = src.shape
                spatial_shapes.append((H, W))

                # flatten
                src = src.flatten(2).transpose(1, 2)  # [B, H*W, hidden_dim]
                mask_l = m.flatten(1)  # [B, H*W]
                pos_l = pos.flatten(2).transpose(1, 2)  # [B, H*W, hidden_dim]

                src_flatten.append(src)
                mask_flatten.append(mask_l)
                lvl_pos_embed_flatten.append(pos_l)

            src_flatten = torch.cat(src_flatten, 1)   # bs, 40320, 256
            lvl_pos_embed_flatten = torch.cat(lvl_pos_embed_flatten, 1) # bs, 40320, 256
            mask_flatten = torch.cat(mask_flatten, 1) # bs, 40320
            spatial_shapes = torch.as_tensor(spatial_shapes, dtype=torch.long, device=srcs[0].device) # num_level, 2
            level_start_index = torch.cat((spatial_shapes.new_zeros((1, )), spatial_shapes.prod(1).cumsum(0)[:-1]))  # num_level
            valid_ratios = torch.stack([self.get_valid_ratio(m) for m in valid_masks], 1) # bs, num_level, 2
            
            memory = self.encoder(src_flatten, spatial_shapes, level_start_index, valid_ratios, lvl_pos_embed_flatten, mask_flatten) # B, 40320, 256
            
            # decoder
            roi_features_attn, _ = self.decoder(
                roi_features_attn, reference_points, memory, 
                spatial_shapes, level_start_index, valid_ratios, query_embed_list)    # [B, Q*H, C]
            
            roi_features_attn_flat = roi_features_attn.view(-1, self.hidden_dim)  # [B*Q*H, hidden_dim]

            gt_indices_all = torch.cat([gt_indices + i * self.num_queries for i, gt_indices in enumerate(gt_indices_list)])
            gt_indices_all = (gt_indices_all.unsqueeze(1) * self.num_hypo + torch.arange(self.num_hypo, device=gt_indices_all.device)).reshape(-1)
            
            roi_features_final = roi_features_attn_flat[gt_indices_all]
            
            #compute heights of projected objects
            #compute scale factor
            scale_box2d_masked_tmp = extract_input_from_tensor(box2d_maps, inds, mask)
            #get coord range of each roi
            coord_ranges_mask2d_tmp = coord_ranges[scale_box2d_masked_tmp[:,0].long()]
            #map box2d coordinate from feature map size domain to original image size domain
            box2d_masked_tmp = torch.cat([scale_box2d_masked_tmp[:,0:1],
                       scale_box2d_masked_tmp[:,1:2]/WIDE  *(coord_ranges_mask2d_tmp[:,1,0:1]-coord_ranges_mask2d_tmp[:,0,0:1])+coord_ranges_mask2d_tmp[:,0,0:1],
                       scale_box2d_masked_tmp[:,2:3]/HEIGHT*(coord_ranges_mask2d_tmp[:,1,1:2]-coord_ranges_mask2d_tmp[:,0,1:2])+coord_ranges_mask2d_tmp[:,0,1:2],
                       scale_box2d_masked_tmp[:,3:4]/WIDE  *(coord_ranges_mask2d_tmp[:,1,0:1]-coord_ranges_mask2d_tmp[:,0,0:1])+coord_ranges_mask2d_tmp[:,0,0:1],
                       scale_box2d_masked_tmp[:,4:5]/HEIGHT*(coord_ranges_mask2d_tmp[:,1,1:2]-coord_ranges_mask2d_tmp[:,0,1:2])+coord_ranges_mask2d_tmp[:,0,1:2]],1)
            roi_calibs_tmp = calibs[box2d_masked_tmp[:,0].long()]

            box2d_height_tmp = torch.clamp(box2d_masked_tmp[:,4]-box2d_masked_tmp[:,2], min=1.0)

            M = gt_indices_all.numel() // self.num_hypo
            cls_ids_m = cls_ids[mask].long()                # [M]
            roi_cal_m = roi_calibs_tmp                      # [M,3,4]
            h2d_m     = box2d_height_tmp                    # [M,1]
            cls_ids_h = cls_ids_m.repeat_interleave(self.num_hypo, dim=0)  # [M*H]
            roi_cal_h = roi_cal_m.repeat_interleave(self.num_hypo, dim=0)  # [M*H,3,4]
            h2d_h     = h2d_m.repeat_interleave(self.num_hypo, dim=0)      # [M*H,1]


            #compute real 3d height
            size3d_offset = self.size_3d(roi_features_final)#[:,:,0,0]
            h3d_log_std = size3d_offset[:,3:4]
            size3d_offset = size3d_offset[:,:3] 
            size_3d = self.mean_size[cls_ids_h] + size3d_offset

            depth_raw = self.depth(roi_features_final)       # [M*H,2]
            depth_geo     = size_3d[:, 0] / h2d_h.squeeze() * roi_cal_h[:, 0, 0]  # [M*H]
            depth_geo_log_std = (h3d_log_std.squeeze() + 2*(roi_cal_h[:,0,0].log() - h2d_h.log())).unsqueeze(-1)  # [M*H,1]
            depth_logstd = torch.logsumexp(torch.cat([depth_raw[:,1:2], depth_geo_log_std], -1), -1, keepdim=True)
            depth_mu = (1. / (depth_raw[:,0:1].sigmoid() + 1e-6) - 1.) + depth_geo.unsqueeze(-1)
            depth_net_out = torch.cat([depth_mu, depth_logstd], -1)         # [M*H,2]

            bb_3d_logit = self.iou3d_conf(roi_features_attn_flat)
            iou_conf = self.iou3d_conf(roi_features_final)
            depth_net_out_conf = self.depth(roi_features_attn_flat)#[:,:,0,0]
            size3d_offset_conf = self.size_3d(roi_features_attn_flat)#[:,:,0,0]
            size3d_offset_conf = size3d_offset_conf[:,:3] 

            cls_rep     = cls_ids_filled[mask_filled].long().repeat_interleave(self.num_hypo, dim=0)  # [B*Q*H]
            roi_cal_rep = roi_calibs.repeat_interleave(self.num_hypo, dim=0)                           # [B*Q*H, 3, 4]
            h2d_rep     = box2d_height.repeat_interleave(self.num_hypo, dim=0)                         # [B*Q*H, 1]

            size_3d_conf   = self.mean_size[cls_rep] + size3d_offset_conf              # [B*Q*H, 3]
            depth_geo_conf = size_3d_conf[:, 0] / h2d_rep.squeeze(-1) * roi_cal_rep[:, 0, 0]   # [B*Q*H]
            depth_conf     = (1. / (depth_net_out_conf[:, 0:1].sigmoid() + 1e-6) - 1.) + depth_geo_conf.unsqueeze(-1)     

            
            res['train_tag'] = torch.ones(o_num_mask_bin*self.num_hypo).type(torch.bool).to(device_id)
            res['heading'] = self.heading(roi_features_final)#[:,:,0,0]
            res['depth'] = depth_net_out
            res['offset_3d'] = self.offset_3d(roi_features_final)#[:,:,0,0]
            res['size_3d']= size3d_offset
            res['h3d_log_variance'] = h3d_log_std
            res['iou_conf'] = iou_conf

            res['indices_conf'] = inds_filled.unsqueeze(-1).expand(BATCH_SIZE, self.num_queries, self.num_hypo).reshape(BATCH_SIZE, -1)  # [B, Q*H]
            res['cls_ids_conf'] = cls_ids_filled.unsqueeze(-1).expand(BATCH_SIZE, self.num_queries, self.num_hypo).reshape(BATCH_SIZE, -1)  # [B, Q*H]
            res['bb_3d_logit'] = bb_3d_logit

            res['heading_conf'] = self.heading(roi_features_attn_flat)#[:,:,0,0]
            res['depth_conf'] = depth_conf
            res['offset_3d_conf'] = self.offset_3d(roi_features_attn_flat)#[:,:,0,0]
            res['size_3d_conf']= size3d_offset_conf
            
        else:
            res['depth'] = torch.zeros([1,2]).to(device_id)
            res['offset_3d'] = torch.zeros([1,2]).to(device_id)
            res['size_3d'] = torch.zeros([1,3]).to(device_id)
            res['train_tag'] = torch.zeros(1).type(torch.bool).to(device_id)
            res['heading'] = torch.zeros([1,24]).to(device_id)
            res['h3d_log_variance'] = torch.zeros([1,1]).to(device_id)
            res['cls_ids_conf'] = torch.zeros(1).to(device_id)
            res['indices_conf'] = torch.zeros(1).to(device_id)
            res['bb_3d_logit'] = torch.zeros(1).to(device_id)
            res['iou_conf'] = torch.zeros(1).to(device_id)
            res['heading_conf'] = torch.zeros([1,24]).to(device_id)
            res['depth_conf'] = torch.zeros(1).to(device_id)
            res['offset_3d_conf'] = torch.zeros([1,2]).to(device_id)
            res['size_3d_conf']= torch.zeros([1,3]).to(device_id)

        return res

    def get_roi_feat(self, feat, inds, mask, srcs, valid_masks, pos_embeds, ret, calibs, coord_ranges, cls_ids):
        BATCH_SIZE,_,HEIGHT,WIDE = feat.size()
        device_id = feat.device
        coord_map = torch.cat([torch.arange(WIDE).unsqueeze(0).repeat([HEIGHT,1]).unsqueeze(0),\
                        torch.arange(HEIGHT).unsqueeze(-1).repeat([1,WIDE]).unsqueeze(0)],0).unsqueeze(0).repeat([BATCH_SIZE,1,1,1]).type(torch.float).to(device_id)
        box2d_centre = coord_map + ret['offset_2d']
        box2d_maps = torch.cat([box2d_centre-ret['size_2d']/2,box2d_centre+ret['size_2d']/2],1)
        box2d_maps = torch.cat([torch.arange(BATCH_SIZE).unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).repeat([1,1,HEIGHT,WIDE]).type(torch.float).to(device_id),box2d_maps],1)
        #box2d_maps is box2d in each bin
        res = self.get_roi_feat_by_mask(feat, box2d_maps, inds,mask, calibs, coord_ranges, cls_ids, ret, srcs, valid_masks, pos_embeds)
        return res

    def get_proposal_pos_embed(self, proposals):
        num_pos_feats = 128
        temperature = 10000
        scale = 2 * math.pi

        dim_t = torch.arange(num_pos_feats, dtype=torch.float32, device=proposals.device)
        dim_t = temperature ** (2 * (dim_t // 2) / num_pos_feats)
        # N, L, 4
        # proposals = proposals.sigmoid() * scale
        proposals = proposals.clamp(0, 1) * scale
        # N, L, 4, 128
        pos = proposals[:, :, :, None] / dim_t
        # N, L, 4, 64, 2
        pos = torch.stack((pos[:, :, :, 0::2].sin(), pos[:, :, :, 1::2].cos()), dim=4).flatten(2)
        return pos

    def get_valid_ratio(self, mask):
        _, H, W = mask.shape
        valid_H = torch.sum(~mask[:, :, 0], 1)
        valid_W = torch.sum(~mask[:, 0, :], 1)
        valid_ratio_h = valid_H.float() / H
        valid_ratio_w = valid_W.float() / W
        valid_ratio = torch.stack([valid_ratio_w, valid_ratio_h], -1)
        return valid_ratio
    

    def project2rect(self,calib,point_img):
        c_u = calib[:,0,2]
        c_v = calib[:,1,2]
        f_u = calib[:,0,0]
        f_v = calib[:,1,1]
        b_x = calib[:,0,3]/(-f_u) # relative
        b_y = calib[:,1,3]/(-f_v)
        x = (point_img[:,0]-c_u)*point_img[:,2]/f_u + b_x
        y = (point_img[:,1]-c_v)*point_img[:,2]/f_v + b_y
        z = point_img[:,2]
        centre_by_obj = torch.cat([x.unsqueeze(-1),y.unsqueeze(-1),z.unsqueeze(-1)],-1)
        return centre_by_obj

    def fill_fc_weights(self, layers):
        for m in layers.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.normal_(m.weight, std=0.001)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)